port: 3000
db:
  type: postgres
  host: localhost
  port: 5432
  user: wikijs
  pass: "{{ wikijs_password }}"
  db: wikijs
  ssl: false


ssl:
  enabled: false

bindIP: 0.0.0.0
logLevel: info
uploads:
  maxFileSize: 5242880
  maxFiles: 10

offline: false
ha: false
dataPath: /var/cache/wikijs/data
